import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import {
  createPresignedUploadUrl,
  createMultipartUpload,
  getPartUploadUrl,
} from '@/lib/r2';

const MULTIPART_THRESHOLD = 100 * 1024 * 1024; // 100MB
const PART_SIZE = 50 * 1024 * 1024; // 50MB

export async function POST(request: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await request.json();
  const { source, fileSize } = body as {
    source: 'desktop' | 'extension' | 'web';
    fileSize: number;
  };

  // Create video row — share_token is auto-generated by DB
  const { data: video, error: insertError } = await supabase
    .from('videos')
    .insert({ user_id: user.id, source, status: 'uploading' })
    .select('id, share_token')
    .single();

  if (insertError || !video) {
    return NextResponse.json(
      { error: 'Failed to create video' },
      { status: 500 },
    );
  }

  const r2Key = `raw/${video.id}.webm`;
  const shareUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/share/${video.share_token}`;

  if (fileSize && fileSize > MULTIPART_THRESHOLD) {
    // Multipart upload
    const uploadId = await createMultipartUpload(r2Key);
    const numParts = Math.ceil(fileSize / PART_SIZE);
    const presignedUrls: string[] = [];

    for (let i = 1; i <= numParts; i++) {
      const url = await getPartUploadUrl(r2Key, uploadId, i);
      presignedUrls.push(url);
    }

    // Track upload session
    await supabase.from('upload_sessions').insert({
      video_id: video.id,
      user_id: user.id,
      r2_upload_id: uploadId,
      r2_key: r2Key,
    });

    return NextResponse.json({
      videoId: video.id,
      shareToken: video.share_token,
      shareUrl,
      uploadType: 'multipart',
      uploadId,
      r2Key,
      presignedUrls,
      partSize: PART_SIZE,
    });
  }

  // Simple single-part upload
  const presignedUrl = await createPresignedUploadUrl(r2Key);

  return NextResponse.json({
    videoId: video.id,
    shareToken: video.share_token,
    shareUrl,
    uploadType: 'single',
    presignedUrl,
    r2Key,
  });
}
